---
- name: install packages
  hosts: group3
  become: true
  tasks:
  - name: Install packages
    package:
      name: "{{ item }}"
      state: present
    loop:
    - package1
    - package2
    - package3
